In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [3]:
2 ** np.arange(1, 21) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [4]:
sum(0.1 ** (3 * np.arange(6)) * 0.2 ** (4 * np.arange(6)))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [5]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
X = np.random.random((5, 2))
print(X)
Z,Y = X[:,0], X[:,1]
print(np.hypot(Z, Y))
print(np.arctan2(Y,Z))

[[0.46485619 0.12798948]
 [0.18560589 0.28270449]
 [0.57684387 0.07113769]
 [0.88777017 0.45858445]
 [0.83109272 0.76049727]]
[0.48215411 0.33818837 0.58121375 0.99921748 1.12653061]
[0.26867424 0.98983956 0.12270273 0.4768058  0.74107191]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [11]:
X = np.random.random((10, 10))
np.argmax(X)

33

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [73]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
Z = (X - np.ones((10, 2))*y)**2
np.argmin((Z.sum(axis=1))**(1/2))

4

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [13]:
X = np.arange(-3, 0)
Y = np.arange(0, 3)
Z = np.arange(2, 4)
np.concatenate([X * X + 2 * X + 6, Y + 6, Z * Z + 4 * Z - 4])


array([ 9,  6,  5,  6,  7,  8,  8, 17])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [97]:
X = np.random.random((10, 10))
average = np.transpose(np.ones((10, 10)) * X.mean(axis=1))
X - average

array([[ 0.33519083, -0.23150702,  0.18401186, -0.30501347,  0.39559013,
        -0.17372825, -0.00784975, -0.19887805, -0.22643521,  0.22861893],
       [ 0.26563073,  0.23188987,  0.20609189,  0.00144867, -0.53342408,
         0.32282022,  0.04876018, -0.09281949, -0.40655422, -0.04384376],
       [-0.05140521,  0.07934736,  0.11172372, -0.2089811 ,  0.05614823,
         0.49413396, -0.11443369, -0.42040309, -0.45054309,  0.5044129 ],
       [-0.3764457 , -0.38825339,  0.39167522,  0.34723827, -0.15403878,
        -0.43211874,  0.42066544,  0.20926879,  0.24530508, -0.26329619],
       [ 0.4436326 ,  0.26759425,  0.28331826, -0.15951006, -0.49100534,
        -0.18925034, -0.35661069, -0.32350315,  0.42983075,  0.09550372],
       [-0.08061663,  0.4342627 , -0.29730621, -0.10811512, -0.01327284,
         0.0036578 ,  0.493125  ,  0.18637718, -0.30566558, -0.31244631],
       [-0.07749747, -0.09400471,  0.40298208, -0.47225862,  0.07379716,
         0.20947608, -0.2408191 ,  0.37866896

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [42]:
X = np.random.normal(loc=5, scale=2., size=1000)
mean = np.sum(X)/len(X)
disp = np.sum(X * X)/len(X) - mean * mean
print(mean, disp)

4.950680666134494 4.0950311715197


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [163]:
D = np.concatenate((np.arange(0, 5, 2), np.arange(1, 5, 2), np.arange(0, 5, 2), np.arange(1, 5, 2)), axis=0)
np.diag(D[0:5], k=0) + np.diag(D[3:7], k=1) + np.diag(D[3:7], k=-1) + \
np.diag(D[1:4], k=2) + np.diag(D[1:4], k=-2) + np.diag(D[4:6], k=3) + np.diag(D[4:6], k=-3) + \
np.diag(D[2:3], k=4) + np.diag(D[2:3], k=-4)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]])